### ISSUE TITLE
modulo operations cause a FS001

### ISSUE THREAD

**Issue by fscherf** [MichaelKim0407/flake8-use-fstring#20]
When using ``%`` for modulo like in ``10 % 2 == 0``, flake8-use-fstrings seems to think python2.7 style string formatting is used

**Comment by MichaelKim0407** [comment]
Are you using the default greedy level?

**Comment by fscherf** [comment]
@MichaelKim0407 its set to ``2`` (https://github.com/lona-web-org/lona/blob/master/flake8.ini#L21)

**Comment by MichaelKim0407** [comment]
Working as intended. Please refer to readme.

Depending on your project (whether you use `%` for maths a lot), my suggestions are:
- set a different greedy level; or
- `noqa` the line containing the operator

**Comment by fscherf** [comment]
@MichaelKim0407 Oh! I am sorry, i missed that. Thanks for the fast response!

**Comment by MichaelKim0407** [comment]
No problem!
